services:
    newscoop_github_latest_commits.lifecyclesubscriber:
        class: Newscoop\GithubLatestCommitsBundle\EventListener\LifecycleSubscriber
        arguments:
            - @em
        tags:
            - { name: kernel.event_subscriber}